general.import = [ "colors.toml" ]

[env]
TERM = "xterm-256color"

[terminal]
osc52 = "CopyPaste"
shell = { program = "/bin/zsh" }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 13

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.65

[keyboard]
bindings = [
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" }
]

