"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#a7c080)\
$os\
$username\
[](bg:#e69875 fg:#a7c080)\
$directory\
[](fg:#e69875 bg:#d699b6)\
$git_branch\
$git_status\
[](fg:#d699b6 bg:#7fbbb3)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#7fbbb3 bg:#83c092)\
$docker_context\
[](fg:#83c092 bg:#3a515d)\
$time\
[](fg:#3a515d)\
\n\
\n$character
"""

[username]
show_always = true
style_user = "bg:#a7c080 fg:#2f383e"
style_root = "bg:#a7c080 fg:#2f383e"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#a7c080 fg:#2f383e"
disabled = true

[directory]
style = "bg:#e69875 fg:#2f383e"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#d699b6 fg:#2f383e"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#d699b6 fg:#2f383e"
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = " "
style = "bg:#7fbbb3 fg:#2f383e"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#7fbbb3 fg:#2f383e"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:#7fbbb3 fg:#2f383e"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#7fbbb3 fg:#2f383e"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:#7fbbb3 fg:#2f383e"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#7fbbb3 fg:#2f383e"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#7fbbb3 fg:#2f383e"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#7fbbb3 fg:#2f383e"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#7fbbb3 fg:#2f383e"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#7fbbb3 fg:#2f383e"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#7fbbb3 fg:#2f383e"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#7fbbb3 fg:#2f383e"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#7fbbb3 fg:#2f383e"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#83c092 fg:#2f383e"
format = '[ $symbol $context ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#3a515d fg:#d3c6aa"
format = '[ ♥ $time ]($style)'
