bg0 = "#282828"
bg1 = "#3c3836"
bg2 = "#504945"
bg3 = "#665c54"
bg4 = "#7c6f64"

fg0 = "#d4be98"
fg1 = "#bdae93"
fg2 = "#a89984"

accent = "#7daea3"

red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
cyan = "#89b482"
purple = "#d3869b"
