bg0 = "#2e3440"
bg1 = "#3b4252"
bg2 = "#4c566a"
bg3 = "#434c5e"
bg4 = "#616e88"

fg0 = "#d8dee9"
fg1 = "#e5e9f0"
fg2 = "#eceff4"

accent = "#81a1c1"

red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
cyan = "#88c0d0"
purple = "#b48ead"
