bg0 = "#282a36"
bg1 = "#44475a"
bg2 = "#373844"
bg3 = "#3d4051"
bg4 = "#6272a4"
fg0 = "#f8f8f2"
fg1 = "#e2e2dc"
fg2 = "#c8c8c0"
accent = "#bd93f9"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#6272a4"
cyan = "#8be9fd"
purple = "#bd93f9"
