bg0 = "#2d353b"
bg1 = "#475258"
bg2 = "#4f585e"
bg3 = "#56635f"
bg4 = "#606b6f"

fg0 = "#d3c6aa"
fg1 = "#d3c6aa"
fg2 = "#a6a391"

accent = "#7fbbb3"

red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
cyan = "#83c092"
purple = "#d699b6"
