bg0 = "#ffffff"
bg1 = "#c0c0c0"
bg2 = "#e0e0e0"
bg3 = "#d0d0d0"
bg4 = "#f2f2f2"

fg0 = "#000000"
fg1 = "#2a2a2a"
fg2 = "#4a4a4a"

accent = "#6e6e6e"

red = "#2a2a2a"
green = "#3a3a3a"
yellow = "#4a4a4a"
blue = "#1a1a1a"
cyan = "#3e3e3e"
purple = "#2e2e2e"
